### ISSUE TITLE
Asyncio Error: Task exception was never retrieved

### ISSUE THREAD

**Issue by so-saf** [vovadenisov/centrifuge-python#19]
Hello! First of all, thank you and your team very much for the project!

Today I caught such a strange error (Sorry for the screenshot, there is only one):

```text
2024-09-02 20:13:07,492 - root - INFO - subscribing: SubscribingContext(code=1, reason='transport closed')
2024-09-02 20:13:07,493 - root - INFO - disconnected: DisconnectedContext (code=1, reason='transport closed')
2024-09-02 20:13:07,720 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-103607' coro=<Client._reconnect() done, defined at /code/.venv/lib/python3.12/site-packages/centrifuge/client.py:280> exception=InvalidStatusCode(503, Headers([('Date', 'Mon, 02 Sep 17:13:07 GMT'), ('Content-Type', 'text/html'), ('Content-Length', '190'), ('Connection', 'keep-alive'), ('Strict-Transport-Security', 'max-age=15724800; includeSubDomains')]))> 
Traceback (most recent call last):
    File "/code/.venv/lib/python3.12/site-packages/centrifuge/client.py", line 283, in _reconnect
        await self._create_connection()
    File "/code/.venv/lib/python3.12/site-packages/centrifuge/client.py", line 296, in _create_connection
        self._conn = await websockets.connect(
                              ^^^^^^^^^^^^^^^^^^^^^^
    File "/code/.venv/lib/python3.12/site-packages/websockets/legacy/client.py", line 655, in __await_impl_timeout__ 
        return await self.__await_impl__()
                    ^^^^^^^^^^^^^^^^^^^^^^
    File "/code/.venv/lib/python3.12/site-packages/websockets/legacy/client.py", line 662, in __await_impl__ 
        await protocol.handshake(
    File "/code/.venv/lib/python3.12/site-packages/websockets/legacy/client.py", line 329, in handshake
        raise InvalidStatusCode (status_code, response_headers)
websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 503
```

As I understand it, the main task fell, but others continued to work, so the program itself did not end.

Perhaps one solution would be to catch the `InvalidHandshake` error

```python
 try:
      self._conn = await websockets.connect(
          self._address,
          subprotocols=subprotocols,
          extra_headers=self._headers,
      )
  except OSError as e:
      handler = self.events.on_error
      await handler(ErrorContext(code=_code_number(_ErrorCode.TRANSPORT_CLOSED), error=e))
      asyncio.ensure_future(self._schedule_reconnect())
      return False
  except InvalidHandshake as e:
      handler = self.events.on_error
      await handler(..., error=e))
      asyncio.ensure_future(self._schedule_reconnect())
      return False

```

**Comment by FZambia** [comment]
Thanks for the report! Fixed in https://github.com/centrifugal/centrifuge-python/releases/tag/0.3.1
